steps:
  - label: ":whale: Build"
    command: docker/build

  - wait

  - label: ":hammer: Test"
    command: docker/test

  - wait

  - label: ":shipit: Push images"
    command: docker/push

  - wait

notify:
  - email: "r.ashton@imperial.ac.uk"
    if: build.state != "passed"
