#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

# In case we switch agents between steps
[ ! -z $(docker images -q $TAG_SHA) ] || docker pull $TAG_SHA

echo "*** starting container"
docker run --rm $TAG_SHA
